apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend/deploy.yml
- frontend/deploy.yml
- backend/service.yml
- frontend/service.yml

images:
- name: 381491977261.dkr.ecr.us-east-1.amazonaws.com/workshop-na-nuvem/production/backend
  newName: 381491977261.dkr.ecr.us-east-1.amazonaws.com/workshop-na-nuvem/production/backend
  newTag: 0c9d0cc065a6401d86c6fd269dec0d60ea57c8ea
- name: 381491977261.dkr.ecr.us-east-1.amazonaws.com/workshop-na-nuvem/production/frontend
  newName: 381491977261.dkr.ecr.us-east-1.amazonaws.com/workshop-na-nuvem/production/frontend
  newTag: 74b00cd2e522f70d594076bc62e073bb4a31ae15
